services:
  # vall-e-x
  vall-e-x:
    build:
      context: ./services/vall-e-x-api
      dockerfile: Dockerfile
    container_name: vall-e-x
    ports:
      - 8080:80
    volumes:
      - ./services/vall-e-x-api:/app

  # minio
  minio:
    image: minio/minio:RELEASE.2023-12-20T01-00-02Z.fips
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - ./containers/minio/data:/data
    command: server --address :9000 --console-address :9001 /data